[package]
name = "pypermu"
version = "0.1.0"
authors = ["mikelma <mikelma7@gmail.com>"]
edition = "2018"

[dependencies]
rayon = "1.5"
rand = "0.8.4"

[lib]
name = "pypermu"
crate-type = ["cdylib", "rlib"]

[dependencies.pyo3]
version = "0.12.1"
features = ["extension-module"]
